### PR TITLE
Ex doc fixes

### PR DESCRIPTION
**Pull request by PatrikStenmark**
I really wanted the link to source and links directly to functions in ex_doc, so here it is :)

### CODE REVIEW

**Comment by obrok** [comment]
Looks good, thanks for this!

**Comment by obrok** [comment]
.... aaaand published.

**Comment by PatrikStenmark** [comment]
It seems something is a bit wrong with the published docs. The GitHub links work, but the menu is acting weird. 

When I click "Modules", nothing happens. When I click on one of the links under "Lens", for example "Upgrading" it behaves differently than on my local machine. It does scroll to the right place, but locally the link gets a little "·" before and changes color. This does not happen on hexdocs. 

Is this some cache issue for me, some files being left from the old version? Or something else? 

Sorry for creating more work for you 😳

**Comment by obrok** [comment]
You're right. I had some old files in `/doc` on my machine that didn't get rebuilt, it seems. Recompiled it and published a fixed version. Thanks for noticing!

**Pull request merged**
